In [98]:
import torch
from torch import nn
whT = torch.tensor([[1., 2.],[3.,1.]], requires_grad=True)
wxT=torch.tensor([[1.],[3.]], requires_grad=True)
wyT=torch.tensor([[3.,1.]], requires_grad=True)
bn = torch.tensor([[1.],[2.]], requires_grad=True)
by = torch.tensor([1.], requires_grad=True)
x1= -1
x2= -0
y1=torch.tensor([0.], requires_grad=False)
y2=torch.tensor([1.], requires_grad=False)
h0=torch.tensor([[2.],[1.]], requires_grad=False)

In [99]:
q1=wxT*x1+torch.matmul(whT, h0)+bn

In [100]:
m = nn.Sigmoid()
h1=m(q1)
p1=torch.matmul(wyT, h1)+by
y_hat_1=m(p1)

In [117]:
p1

tensor([[4.9436]], grad_fn=<AddBackward0>)

In [101]:
y_hat_1

tensor([[0.9929]], grad_fn=<SigmoidBackward>)

In [102]:
q2=wxT*x2+torch.matmul(whT, h1)+bn
h2=m(q2)
p2=torch.matmul(wyT, h2)+by
y_hat_2=m(p2)

In [104]:
L=1/2*((y1-y_hat_1)**2+(y2-y_hat_2)**2)

In [106]:
L

tensor([[0.4930]], grad_fn=<MulBackward0>)

In [107]:
external_grad = torch.tensor([[1.]])
L.backward(gradient=external_grad)

In [108]:
whT.grad

tensor([[7.3682e-04, 3.6704e-04],
        [3.4270e-05, 1.7069e-05]])

In [109]:
wyT.grad

tensor([[0.0068, 0.0069]])

In [112]:
wxT.grad

tensor([[-3.6974e-04],
        [-1.7199e-05]])

In [113]:
by.grad

tensor([0.0069])

In [115]:
bn.grad

tensor([[3.6703e-04],
        [1.7069e-05]])

In [66]:
p1

tensor([[4.9436]], grad_fn=<AddBackward0>)